import { invoke } from "@tauri-apps/api/core";
import {
    userService,
    type SyncData,
    type UserInitData,
} from "@features/auth/userService";
import { settingsService } from "@services/settings/settingsService";
import { globalUserStatus } from "@features/auth/useUserStatus";
import { maxIsoTimestamp } from "@shared/utils/utils";

export type ToastFunction = (message: string, type: string) => void;
export type TranslateFunction = (
    key: string,
    params?: Record<string, any>
) => string;

interface SyncServiceState {
    isOnline: boolean;
    isSyncing: boolean;
    lastSyncTime: string | null;
    hasCloudData: boolean;
    autoSyncEnabled: boolean;
}

class SyncService {
    private state: SyncServiceState = {
        isOnline: navigator.onLine,
        isSyncing: false,
        lastSyncTime: null,
        hasCloudData: false,
        autoSyncEnabled: true,
    };

    private listeners: ((state: SyncServiceState) => void)[] = [];
    private autoSyncInterval: number | null = null;

    constructor() {
        window.addEventListener("online", () => {
            this.state.isOnline = true;
            this.notifyListeners();
            if (this.state.autoSyncEnabled && this.isAuthenticated()) {
                this.autoSync().then((r) => {
                    console.log("Auto-sync completed:", r);
                });
            }
        });

        window.addEventListener("offline", () => {
            this.state.isOnline = false;
            this.notifyListeners();
        });

        this.startAutoSync();
    }

    subscribe(listener: (state: SyncServiceState) => void) {
        this.listeners.push(listener);
        return () => {
            this.listeners = this.listeners.filter((l) => l !== listener);
        };
    }

    private notifyListeners() {
        this.listeners.forEach((listener) => listener({ ...this.state }));
    }

    private startAutoSync() {
        if (this.autoSyncInterval) return;

        this.autoSyncInterval = setInterval(
            () => {
                if (
                    this.state.isOnline &&
                    this.state.autoSyncEnabled &&
                    !this.state.isSyncing &&
                    this.isAuthenticated()
                ) {
                    this.autoSync().then((r) => {
                        console.log("Auto-sync completed:", r);
                    });
                }
            },
            5 * 60 * 1000
        ) as unknown as number;
    }

    private isAuthenticated(): boolean {
        return !!globalUserStatus?.isAuthenticated?.value;
    }

    private isAutoGeneratedAccount(account: any): boolean {
        return (
            Array.isArray(account?.tags) &&
            account.tags.includes("auto-generated")
        );
    }

    private async autoSync() {
        try {
            await Promise.all([this.downloadFromCloud(), this.uploadToCloud()]);
        } catch (error) {
            console.warn("Auto-sync failed:", error);
        }
    }

    async initializeSyncStatus() {
        if (!this.state.isOnline || !this.isAuthenticated()) return;

        try {
            const status = await userService.getSyncStatus();
            if (!status) return;

            this.state.lastSyncTime = status.last_sync_timestamp;
            this.state.hasCloudData = status.has_cloud_data;
            this.notifyListeners();
        } catch (error) {
            console.error("Failed to get sync status:", error);
        }
    }

    hydrateSyncStatus(data: UserInitData) {
        if (!this.state.isOnline) return;

        try {
            const settingsPref =
                data.preferences.find(
                    (p) => p.key === "collapseloader.settings"
                ) || null;

            const lastSync = maxIsoTimestamp([
                settingsPref?.updated_at ?? null,
                ...data.favorites.map((f) => f.created_at ?? null),
                ...data.accounts.map((a) => a.updated_at ?? null),
            ]);

            this.state.lastSyncTime = lastSync;
            this.state.hasCloudData =
                !!settingsPref ||
                data.favorites.length > 0 ||
                data.accounts.length > 0;
            this.notifyListeners();
        } catch (error) {
            console.error("Failed to hydrate sync status:", error);
        }
    }

    async checkAndRestoreOnStartup(): Promise<void> {
        if (!this.state.isOnline) {
            console.log("Offline - skipping startup sync check");
            return;
        }

        if (!this.isAuthenticated()) {
            console.log(
                "User not authenticated - skipping startup sync restore"
            );
            return;
        }

        try {
            await this.initializeSyncStatus();

            if (!this.state.hasCloudData) {
                console.log(
                    "No cloud data available - skipping startup restore"
                );
                return;
            }

            console.log("Checking for startup sync restoration...");

            await this.downloadFromCloud();

            console.log("Startup sync restoration completed");
        } catch (error) {
            console.warn(
                "Failed to check/restore synced data on startup:",
                error
            );
        }
    }

    async uploadToCloud(): Promise<boolean> {
        if (
            !this.state.isOnline ||
            this.state.isSyncing ||
            !this.isAuthenticated()
        ) {
            return false;
        }

        this.state.isSyncing = true;
        this.notifyListeners();

        try {
            await settingsService.loadSettings();
            const settings = settingsService.getSettings();
            const [favorites, accounts] = await Promise.all([
                invoke<number[]>("get_favorite_clients"),
                invoke<any[]>("get_accounts"),
            ]);

            const accountsToSync = (accounts || []).filter(
                (acc) => !this.isAutoGeneratedAccount(acc)
            );

            if (accountsToSync.length !== (accounts?.length ?? 0)) {
                console.debug(
                    "Skipping auto-generated local accounts from sync",
                    (accounts?.length ?? 0) - accountsToSync.length
                );
            }

            const syncData: SyncData = {
                settings_data: settings,
                favorites_data: favorites,
                accounts_data: accountsToSync,
            };

            await userService.syncToCloud(syncData);

            const status = await userService.getSyncStatus();
            if (status) {
                this.state.lastSyncTime =
                    status.last_sync_timestamp || new Date().toISOString();
            }

            this.state.hasCloudData = true;
            return true;
        } catch (error) {
            console.error("Failed to upload to cloud:", error);
            throw error;
        } finally {
            this.state.isSyncing = false;
            this.notifyListeners();
        }
    }

    async restoreFromInitData(data: UserInitData): Promise<void> {
        if (!this.state.isOnline) return;

        this.hydrateSyncStatus(data);

        if (!this.state.hasCloudData) return;

        try {
            const syncData = userService.formatSyncData(
                data.preferences,
                data.favorites,
                data.accounts
            );
            await this.restoreData(syncData);
        } catch (error) {
            console.error("Failed to restore from init data:", error);
        }
    }

    private async restoreSettings(settingsData: any) {
        if (!settingsData || Object.keys(settingsData).length === 0) return;

        await settingsService.loadSettings();
        const currentSettings = settingsService.getSettings();
        const mergedSettings = { ...currentSettings };

        for (const key in settingsData) {
            if (mergedSettings[key]) {
                mergedSettings[key].value = settingsData[key].value;
            } else {
                mergedSettings[key] = settingsData[key];
            }
        }

        await settingsService.saveSettings(mergedSettings as any);
        await settingsService.loadSettings();
    }

    private async restoreFavorites(favoritesData: any) {
        if (!Array.isArray(favoritesData)) return;

        try {
            const currentFavorites = await invoke<number[]>(
                "get_favorite_clients"
            );
            const favoritesChanged =
                favoritesData.length !== currentFavorites.length ||
                !favoritesData.every((id: number) =>
                    currentFavorites.includes(id)
                );

            if (favoritesChanged) {
                await invoke("set_all_favorites", {
                    clientIds: favoritesData,
                });
            }
        } catch (e) {
            console.warn(
                "Failed to set all favorites, falling back to loop",
                e
            );
            const currentFavorites = await invoke<number[]>(
                "get_favorite_clients"
            );
            for (const clientId of currentFavorites) {
                await invoke("remove_favorite_client", { clientId });
            }
            for (const clientId of favoritesData) {
                await invoke("add_favorite_client", { clientId });
            }
        }
    }

    private async restoreAccounts(accountsData: any) {
        if (!Array.isArray(accountsData)) return;

        try {
            const localAccounts = await invoke<any[]>("get_accounts");
            const localUsernames = new Set(
                localAccounts.map((acc: any) => acc.username)
            );

            for (const cloudAccount of accountsData) {
                if (this.isAutoGeneratedAccount(cloudAccount)) continue;
                if (
                    !cloudAccount.username ||
                    localUsernames.has(cloudAccount.username)
                )
                    continue;

                try {
                    await invoke("add_account", {
                        username: cloudAccount.username,
                        tags: cloudAccount.tags || ["cloud-sync"],
                    });
                } catch (error) {
                    console.warn(
                        "Failed to add cloud account:",
                        cloudAccount.username,
                        error
                    );
                }
            }
        } catch (error) {
            console.error("Failed to restore accounts:", error);
        }
    }

    private async restoreData(cloudData: SyncData): Promise<boolean> {
        if (!cloudData) return false;

        await Promise.all([
            this.restoreSettings(cloudData.settings_data),
            this.restoreFavorites(cloudData.favorites_data),
            this.restoreAccounts(cloudData.accounts_data),
        ]);

        this.state.lastSyncTime =
            cloudData.last_sync_timestamp || new Date().toISOString();
        this.state.hasCloudData = true;
        this.notifyListeners();

        return true;
    }

    async downloadFromCloud(): Promise<boolean> {
        if (!this.state.isOnline || this.state.isSyncing) return false;
        if (!this.isAuthenticated()) return false;

        this.state.isSyncing = true;
        this.notifyListeners();

        try {
            const cloudData = await userService.downloadFromCloud();

            if (!cloudData) return false;

            return await this.restoreData(cloudData);
        } catch (error) {
            console.error("Failed to download from cloud:", error);
            throw error;
        } finally {
            this.state.isSyncing = false;
            this.notifyListeners();
        }
    }

    async manualSync(
        addToast: ToastFunction,
        t: TranslateFunction
    ): Promise<void> {
        if (typeof addToast !== "function") {
            console.error("addToast is not a function:", addToast);
            return;
        }

        if (typeof t !== "function") {
            console.error("t (translation function) is not a function:", t);
            return;
        }

        if (!this.isAuthenticated()) {
            addToast(t("toast.sync.login_required"), "error");
            return;
        }

        if (!this.state.isOnline) {
            addToast(t("toast.sync.offline_error"), "error");
            return;
        }

        if (this.state.isSyncing) {
            addToast(t("toast.sync.already_in_progress"), "info");
            return;
        }

        try {
            addToast(t("toast.sync.syncing"), "info");

            await this.downloadFromCloud();
            await this.uploadToCloud();
            addToast(t("toast.sync.success"), "success");
        } catch (error) {
            addToast(t("toast.sync.failed", { error }), "error");
        }
    }

    getState(): SyncServiceState {
        return { ...this.state };
    }

    setAutoSyncEnabled(enabled: boolean) {
        this.state.autoSyncEnabled = enabled;
        this.notifyListeners();
    }

    destroy() {
        if (this.autoSyncInterval) {
            clearInterval(this.autoSyncInterval);
            this.autoSyncInterval = null;
        }
    }
}

export const syncService = new SyncService();
export type { SyncServiceState };
